version: '2'
services:
  zookeeper:
    image: myimagestore/zookeeper
    ports:
      - "8080:8080"
  kafka:
      image: myimagestore/kafka
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
