server:
  port: 9000

  spring:
    kafka:
      consumer:
        bootstrap-servers: localhost:9092
        group-id: group-id
        auto-offer-reset: earlist
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


      producer:
        bootstrap-servers: localhost:9092
          group-id: group-id
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.apache.kafka.common.serialization.StringSerializer